name: idsplat
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils_impl_linux-64=2.40=h5293946_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - expat=2.7.1=h6a678d5_0
  - gcc=11.4.0=h602e360_13
  - gcc_impl_linux-64=11.4.0=h00c12a0_13
  - gxx=11.4.0=h602e360_13
  - gxx_impl_linux-64=11.4.0=h634f3ee_13
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-devel_linux-64=11.4.0=h8f596e0_113
  - libgcc-ng=15.1.0=h69a702a_2
  - libgomp=15.1.0=h767d61c_2
  - libsanitizer=11.4.0=h5763a12_13
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-devel_linux-64=11.4.0=h8f596e0_113
  - libstdcxx-ng=15.1.0=h4852527_2
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.5.0=h7b32b05_1
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.0
      - addict==2.4.0
      - annotated-types==0.7.0
      - astroid==2.11.7
      - asttokens==3.0.0
      - attrs==25.3.0
      - backports-tarfile==1.2.0
      - black==22.3.0
      - blinker==1.9.0
      - build==1.2.2.post1
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cmake==4.0.3
      - comm==0.2.2
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cryptography==45.0.4
      - cycler==0.12.1
      - dash==3.1.0
      - decorator==5.2.1
      - dill==0.4.0
      - docutils==0.21.2
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - execnet==2.1.1
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flask==3.1.1
      - fonttools==4.58.4
      - fsspec==2025.5.1
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.73.0
      - hf-xet==1.1.5
      - huggingface-hub==0.33.0
      - id==1.5.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isort==5.10.1
      - itsdangerous==2.2.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.2.1
      - jaxtyping==0.3.2
      - jedi==0.19.2
      - jeepney==0.9.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - keyring==25.6.0
      - kiwisolver==1.4.8
      - lazy-object-proxy==1.11.0
      - lit==18.1.8
      - loguru==0.7.3
      - lpips==0.1.4
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mediapy==1.2.4
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - narwhals==1.44.0
      - natsort==8.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nh3==0.2.21
      - ninja==1.11.1.4
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - nvitop==1.5.2
      - open-clip-torch==2.32.0
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.3.0
      - parso==0.8.4
      - pathlib==1.0.1
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - plotly==6.2.0
      - pluggy==1.6.0
      - plyfile==1.1.2
      - prompt-toolkit==3.0.51
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py==1.11.0
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pylint==2.13.4
      - pyparsing==3.2.3
      - pyproject-hooks==1.2.0
      - pyquaternion==0.9.9
      - pytest==7.1.2
      - pytest-forked==1.6.0
      - pytest-xdist==2.5.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0
      - readme-renderer==44.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-toolbelt==1.0.0
      - retrying==1.4.0
      - rfc3986==2.0.0
      - rich==14.0.0
      - rpds-py==0.25.1
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - secretstorage==3.3.3
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - simple-knn==0.0.0
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - timm==1.0.15
      - tokenize-rt==6.2.0
      - tomli==2.2.1
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==2.0.0
      - twine==6.1.0
      - typeguard==4.4.4
      - typing==3.7.4.3
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wadler-lindig==0.1.7
      - wandb==0.20.1
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - zipp==3.23.0